apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    editable: false
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: bees
      defaultBucket: bees_raw
      tlsSkipVerify: true
    secureJsonData:
      token: ${GRAFANA_INFLUX_TOKEN}
